image_path: /Users/ladvien/Dropbox/graphics/ml_images/spriter_sheet_ider/combined_annotations
label_path: /Users/ladvien/Dropbox/graphics/ml_images/spriter_sheet_ider/combined_annotations
output_path: output/

settings:
  zoom_factor: 1.0
  pan_factor:
    x: 120.0
    y: 120.0

  key_map:
    zoom_in: 'KeyE'
    zoom_out: 'KeyQ'
    pan_up: 'KeyS'
    pan_down: 'KeyW'
    pan_left: 'KeyD'
    pan_right: 'KeyA'
    # save: 13
    # quit: 27
    # next: 32
    # previous: 8
    # delete: 127
    # undo: 117
    # redo: 114
    # toggle: 116
    # toggle_all

  output_format:
    type: yolo
    project_name: spriter_sheet_ider
    folder_paths:
      train: ./train/
      validation: ./validation/
      test: ./test/
    class_map:
      0: 'horizontal_animation'
      1: 'vertical_animation'