image_path: /Users/ladvien/Dropbox/graphics/ml_images/spriter_sheet_ider/combined_annotations/train/images/
annotation_path: /Users/ladvien/Dropbox/graphics/ml_images/spriter_sheet_ider/combined_annotations/train/annotations/
output_path: output/

settings:
  zoom_factor: 4.0