
project_config:
  source_paths:
    images: /Users/ladvien/rusty_key_labeler/rusty_key_labeler/test_data/input
    labels: /Users/ladvien/rusty_key_labeler/rusty_key_labeler/test_data/input
  type: yolo
  project_name: spriter_sheet_ider
  export:
    paths:
      root: ./rusty_key_labeler/test_data/export/
      # TODO: Update paths to use root and relative paths.
      train: ./rusty_key_labeler/test_data/export/train/
      validation: ./rusty_key_labeler/test_data/export/validation/
      test: ./rusty_key_labeler/test_data/export/test/
    duplicate_tolerance: 0.005
    class_map:
      0: 'horizontal_animation'
      1: 'vertical_animation'
      
    split:
      train: 0.80
      validation: 0.20
      test: 0.0 
  

output_path: output/

settings:
  zoom_factor: 1.1
  pan_factor:
    x: 530.0
    y: 530.0
  bounding_boxes:
    thickness: 5
    corner_radius: 5.0
    class_color_map:
      # RGBA Color
      - (0, 255, 0, 255)
      - (0, 0, 255, 255)

  delay_between_images: 0.1

  ui_panel:
    font: "RobotoMono-Regular.ttf"
    font_size: 20
    colors:
      background: (23, 23, 28, 127)       # Sleek charcoal gray
      text: (222, 235, 250, 255)          # Soft, clean white-blue
      inner_border: (74, 174, 214, 255)   # Calm sky blue
      outer_border: (84, 214, 148, 255)   # Vibrant mint green
      
    top_left_position:
      x: 0
      y: 0
    size:
      width_percentage: 0.2
      height_percentage: 0.1

  key_map:
    zoom_in: 'KeyE'
    zoom_out: 'KeyQ'
    pan_up: 'KeyS'
    pan_down: 'KeyW'
    pan_left: 'KeyD'
    pan_right: 'KeyA'
    # save: 13
    # quit: 27
    # next: 32
    # previous: 8
    # delete: 127
    # undo: 117
    # redo: 114
    # toggle: 116
    # toggle_all

