
project_config:
  source_paths:
    images: rusty_key_labeler/input/yolo_export/
    labels: rusty_key_labeler/input/yolo_export/
  type: yolo
  project_name: spriter_sheet_ider
  export_paths:
    train: ./train/
    validation: ./validation/
    test: ./test/
  duplicate_tolerance: 0.005
  class_map:
    0: 'horizontal_animation'
    1: 'vertical_animation'
  

output_path: output/

settings:
  zoom_factor: 1.0
  pan_factor:
    x: 120.0
    y: 120.0
  key_map:
    zoom_in: 'KeyE'
    zoom_out: 'KeyQ'
    pan_up: 'KeyS'
    pan_down: 'KeyW'
    pan_left: 'KeyD'
    pan_right: 'KeyA'
    # save: 13
    # quit: 27
    # next: 32
    # previous: 8
    # delete: 127
    # undo: 117
    # redo: 114
    # toggle: 116
    # toggle_all

